<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Widget_Model_Base_ConfigCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'config_id',
        'created' => 'config_created',
        'updated' => 'config_updated',
        'position' => 'config_position',
        'data' => 'config_data',
        'widgetId' => 'config_widget_id',
        'layoutId' => 'config_layout_id',
    );
}