<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/Project/Model/Abuse.php
*/
abstract class Plugg_Project_Model_Base_Abuse extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Abuse', $model);
        $this->_vars = array('abuse_id' => 0, 'abuse_created' => 0, 'abuse_updated' => 0, 'abuse_entity' => null, 'abuse_entity_id' => 0, 'abuse_reason' => null, 'abuse_comment' => null, 'abuse_ip' => null, 'abuse_status' => 0, 'abuse_project_id' => null, 'abuse_userid' => null);
    }

    public function getUserId()
    {
        return $this->getVar('userid');
    }

    public function assignUser($user)
    {
        $this->_setVar('userid', $user->getId());
    }

    protected function _fetchUser($withData = false)
    {
        if (!isset($this->_objects['User'])) {
            $user_id = $this->getUserId();
            $identities = $this->_model->fetchUserIdentities(array($user_id), $withData);
            $this->_objects['User'] = $identities[$user_id];
        }
        return $this->_objects['User'];
    }

    public function isOwnedBy($user)
    {
        return $this->getUserId() == $user->getId();
    }

    public function getId()
    {
        return $this->getVar('id');
    }

    public function setId($value)
    {
        $this->setVar('id', $value);
    }

    public function getTimeCreated()
    {
        return $this->getVar('created');
    }

    public function getTimeUpdated()
    {
        return $this->getVar('updated');
    }

    public function assignProject(Sabai_Model_Entity $entity)
    {
        if ($entity->getName() != 'Project') return false;

        return $this->_assignEntity($entity, 'project_id');
    }

    public function unassignProject()
    {
        return $this->_unassignEntity('Project', 'project_id');
    }

    protected function _fetchProject()
    {
        return $this->_fetchEntity('Project', 'project_id');
    }

    protected function _getVar($name)
    {
        return $this->_vars['abuse_' . $name];
    }

    protected function _setVar($name, $value)
    {
        switch ($name) {
        case 'id':
            $this->_vars['abuse_id'] = $value;
            break;
        case 'entity':
            $this->_vars['abuse_entity'] = trim($value);
            break;
        case 'entity_id':
            $this->_vars['abuse_entity_id'] = $value;
            break;
        case 'reason':
            $this->_vars['abuse_reason'] = trim($value);
            break;
        case 'comment':
            $this->_vars['abuse_comment'] = trim($value);
            break;
        case 'ip':
            $this->_vars['abuse_ip'] = trim($value);
            break;
        case 'status':
            $this->_vars['abuse_status'] = $value;
            break;
        case 'project_id':
            $this->_vars['abuse_project_id'] = $value;
            break;
        case 'userid':
            $this->_vars['abuse_userid'] = trim($value);
            break;
        default:
            trigger_error(sprintf('Error trying to set value for variable %s. This variable is either read-only or does not exist for this entity', $name), E_USER_WARNING);
            return false;
        }
        return true;
    }

    protected function _get($name, $sort, $order)
    {
        switch ($name) {
        case 'entity':
            return $this->getVar('entity');
        case 'entity_id':
            return $this->getVar('entity_id');
        case 'reason':
            return $this->getVar('reason');
        case 'comment':
            return $this->getVar('comment');
        case 'ip':
            return $this->getVar('ip');
        case 'status':
            return $this->getVar('status');
        case 'Project':
            return $this->_fetchProject();
        case 'User':
            return $this->_fetchUser();
        case 'UserWithData':
            return $this->_fetchUser(true);
        }
    }

    public function __set($name, $value)
    {
        switch ($name) {
        case 'entity':
            $this->setVar('entity', $value);
            break;
        case 'entity_id':
            $this->setVar('entity_id', $value);
            break;
        case 'reason':
            $this->setVar('reason', $value);
            break;
        case 'comment':
            $this->setVar('comment', $value);
            break;
        case 'ip':
            $this->setVar('ip', $value);
            break;
        case 'status':
            $this->setVar('status', $value);
            break;
        case 'Project':
            $entity = is_array($value) ? $value[0] : $value;
            $this->assignProject($entity);
            break;
        }
    }

    public function initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_Project_Model_Base_AbuseRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Abuse', $model);
    }
    public function fetchByUser($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('abuse_userid', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByUser($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('User', $id, $perpage, $sort, $order);
    }

    public function countByUser($id)
    {
        return $this->_countByForeign('abuse_userid', $id);
    }

    public function fetchByUserAndCriteria($id, Sabai_Model_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('abuse_userid', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByUserAndCriteria($id, Sabai_Model_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('User', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByUserAndCriteria($id, Sabai_Model_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('abuse_userid', $id, $criteria);
    }

    public function fetchByProject($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('abuse_project_id', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByProject($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('Project', $id, $perpage, $sort, $order);
    }

    public function countByProject($id)
    {
        return $this->_countByForeign('abuse_project_id', $id);
    }

    public function fetchByProjectAndCriteria($id, Sabai_Model_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('abuse_project_id', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByProjectAndCriteria($id, Sabai_Model_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('Project', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByProjectAndCriteria($id, Sabai_Model_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('abuse_project_id', $id, $criteria);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_Project_Model_Base_AbusesByRowset($rs, $this->_model->create('Abuse'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_Project_Model_Base_Abuses($this->_model, $entities);
    }
}

class Plugg_Project_Model_Base_AbusesByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Sabai_Model_Entity $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Abuses', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_Project_Model_Base_Abuses extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Abuses', $entities);
    }
}