<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Project_Model_Base_CategoryCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'category_id',
        'created' => 'category_created',
        'updated' => 'category_updated',
        'name' => 'category_name',
        'description' => 'category_description',
        'order' => 'category_order',
    );
}