<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Project_Model_Base_CommentCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'comment_id',
        'created' => 'comment_created',
        'updated' => 'comment_updated',
        'rating' => 'comment_rating',
        'title' => 'comment_title',
        'body' => 'comment_body',
        'bodyHtml' => 'comment_body_html',
        'bodyFilterId' => 'comment_body_filter_id',
        'allowEdit' => 'comment_allow_edit',
        'ip' => 'comment_ip',
        'status' => 'comment_status',
        'projectId' => 'comment_project_id',
        'userid' => 'comment_userid',
    );
}