<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Project/Model/CommentHTMLQuickForm.php
*/
abstract class Plugg_Project_Model_Base_CommentHTMLQuickForm extends Sabai_Model_EntityHTMLQuickForm
{
    public function onInit(array $params)
    {
        $this->addElement('select', 'rating', $this->_model->_('Rating'), null, array('size' => 1));
        $this->setRequired('rating', $this->_model->_('Rating is required'));
        $this->addElement('text', 'title', $this->_model->_('Title'), array('size' => 80, 'maxlength' => 255));
        $this->setRequired('title', $this->_model->_('Title is required'));
        $this->addElement('textarea', 'body', $this->_model->_('Body'), array('rows' => 10, 'cols' => 60));
        $this->setRequired('body', $this->_model->_('Body is required'));
        $this->addElement('altselect', 'allow_edit', $this->_model->_('Allow edit'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('selectmodelentity', $this->_model, 'Project', 'Project', $this->_model->_('project'), null, array('size' => 1));
        $this->addElement('text', 'userid', $this->_model->_('User ID'), array('size' => 30, 'maxlength' => 255));
        $this->_onInit($params);
    }

    public function onEntity(Sabai_Model_Entity $entity)
    {
        $defaults = array();
        foreach (array('rating', 'title', 'body', 'allow_edit') as $key) {
            if ($this->elementExists($key) || $this->isInGroup($key)) {
                $defaults[$key] = $entity->getVar($key);
            }
        }
        if ($this->elementExists('Project')) {
            $defaults['Project'] = $entity->getVar('project_id');
        }
        if ($this->elementExists('userid')) {
            $defaults['userid'] = $entity->getVar('userid');
        }
        if (!empty($defaults)) $this->setDefaults($defaults);
        $this->_onEntity($entity);
    }

    public function onFillEntity(Sabai_Model_Entity $entity)
    {
        $vars = array();
        foreach (array('rating' => 'rating', 'title' => 'title', 'body' => 'body', 'allow_edit' => 'allow_edit', 'project_id' => 'Project', 'userid' => 'userid') as $var_name => $form_name) {
            if ($this->elementExists($form_name) || $this->isInGroup($form_name)) {
                if ($this->getElementType($form_name) == 'static') continue;

                $value = $this->getSubmitValue($form_name);
                $vars[$var_name] = is_array($value) ? array_shift($value) : $value;
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    abstract protected function _onInit(array $params);
    abstract protected function _onEntity(Sabai_Model_Entity $entity);
    abstract protected function _onFillEntity(Sabai_Model_Entity $entity);
}