<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Project_Model_Base_DeveloperCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'developer_id',
        'created' => 'developer_created',
        'updated' => 'developer_updated',
        'role' => 'developer_role',
        'status' => 'developer_status',
        'tasks' => 'developer_tasks',
        'projectId' => 'developer_project_id',
        'userid' => 'developer_userid',
    );
}