<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Project_Model_Base_LinkCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'link_id',
        'created' => 'link_created',
        'updated' => 'link_updated',
        'type' => 'link_type',
        'url' => 'link_url',
        'title' => 'link_title',
        'summary' => 'link_summary',
        'summaryHtml' => 'link_summary_html',
        'summaryFilterId' => 'link_summary_filter_id',
        'allowEdit' => 'link_allow_edit',
        'score' => 'link_score',
        'ip' => 'link_ip',
        'status' => 'link_status',
        'projectId' => 'link_project_id',
        'userid' => 'link_userid',
        'linkvoteCount' => 'link_linkvote_count',
        'linkvoteLast' => 'link_linkvote_last',
        'linkvoteLasttime' => 'link_linkvote_lasttime',
    );
}