<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Project/Model/ProjectHTMLQuickForm.php
*/
abstract class Plugg_Project_Model_Base_ProjectHTMLQuickForm extends Sabai_Model_EntityHTMLQuickForm
{
    public function onInit(array $params)
    {
        $this->addElement('text', 'name', $this->_model->_('Name'), array('size' => 80, 'maxlength' => 255));
        $this->setRequired('name', $this->_model->_('Name is required'));
        $this->addElement('textarea', 'summary', $this->_model->_('Summary'), array('rows' => 15, 'cols' => 60));
        $this->setRequired('summary', $this->_model->_('Summary is required'));
        $this->addElement('altselect', 'hidden', $this->_model->_('Hidden'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('altselect', 'allow_comments', $this->_model->_('Allow comments'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('altselect', 'allow_links', $this->_model->_('Allow links'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('altselect', 'allow_images', $this->_model->_('Allow images'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('altselect', 'allow_releases', $this->_model->_('Allow releases'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('text', 'views', $this->_model->_('Views'), array('size' => 10, 'maxlength' => 255));
        $this->addElement('selectmodelentity', $this->_model, 'Category', 'Categories', $this->_model->_('Category'), null, array('size' => 10, 'multiple' => 'multiple'));
        $this->addElement('text', 'userid', $this->_model->_('User ID'), array('size' => 30, 'maxlength' => 255));
        $this->_onInit($params);
    }

    public function onEntity(Sabai_Model_Entity $entity)
    {
        $defaults = array();
        foreach (array('name', 'summary', 'hidden', 'allow_comments', 'allow_links', 'allow_images', 'allow_releases', 'views') as $key) {
            if ($this->elementExists($key) || $this->isInGroup($key)) {
                $defaults[$key] = $entity->getVar($key);
            }
        }
        if ($this->elementExists('Categories')) {
            $defaults['Categories'] = $entity->get('Categories')->getAllIds();
        }
        if ($this->elementExists('userid')) {
            $defaults['userid'] = $entity->getVar('userid');
        }
        if (!empty($defaults)) $this->setDefaults($defaults);
        $this->_onEntity($entity);
    }

    public function onFillEntity(Sabai_Model_Entity $entity)
    {
        $vars = array();
        foreach (array('name' => 'name', 'summary' => 'summary', 'hidden' => 'hidden', 'allow_comments' => 'allow_comments', 'allow_links' => 'allow_links', 'allow_images' => 'allow_images', 'allow_releases' => 'allow_releases', 'views' => 'views', 'userid' => 'userid') as $var_name => $form_name) {
            if ($this->elementExists($form_name) || $this->isInGroup($form_name)) {
                if ($this->getElementType($form_name) == 'static') continue;

                $value = $this->getSubmitValue($form_name);
                $vars[$var_name] = is_array($value) ? array_shift($value) : $value;
            }
        }
        $entity->setVars($vars);
        if ($this->elementExists('Categories')) {
            $entity->set('Categories', (array)$this->getElementValue('Categories'));
        } elseif ($group = $this->isInGroup('Categories')) {
            $value = $this->getElementValue($group);
            $entity->set('Categories', (array)$value['Categories']);
        }
        $this->_onFillEntity($entity);
    }

    abstract protected function _onInit(array $params);
    abstract protected function _onEntity(Sabai_Model_Entity $entity);
    abstract protected function _onFillEntity(Sabai_Model_Entity $entity);
}