<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Project_Model_Base_ReleaseCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'release_id',
        'created' => 'release_created',
        'updated' => 'release_updated',
        'version' => 'release_version',
        'stability' => 'release_stability',
        'date' => 'release_date',
        'downloadUrl' => 'release_download_url',
        'noteUrl' => 'release_note_url',
        'summary' => 'release_summary',
        'summaryHtml' => 'release_summary_html',
        'summaryFilterId' => 'release_summary_filter_id',
        'status' => 'release_status',
        'allowReports' => 'release_allow_reports',
        'allowDownload' => 'release_allow_download',
        'projectId' => 'release_project_id',
        'userid' => 'release_userid',
        'reportCount' => 'release_report_count',
        'reportLast' => 'release_report_last',
        'reportLasttime' => 'release_report_lasttime',
    );
}