<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Project/Model/ReleaseHTMLQuickForm.php
*/
abstract class Plugg_Project_Model_Base_ReleaseHTMLQuickForm extends Sabai_Model_EntityHTMLQuickForm
{
    public function onInit(array $params)
    {
        $this->addElement('text', 'version', $this->_model->_('Version'), array('size' => 80, 'maxlength' => 255));
        $this->setRequired('version', $this->_model->_('Version is required'));
        $this->addElement('select', 'stability', $this->_model->_('Stability'), null, array('size' => 1));
        $options = array(
            'format' => $this->_model->_('F d, Y'),
            'minYear' => 2000,
            'maxYear' => date('Y'),
            'addEmptyOption'   => true,
            'emptyOptionValue' => '',
            'emptyOptionText'  => '&nbsp;'
        );
        $this->addElement('date', 'date', $this->_model->_('Date'), $options);
        $this->addElement('text', 'download_url', $this->_model->_('Download url'), array('size' => 80, 'maxlength' => 255));
        $this->setRequired('download_url', $this->_model->_('Download url is required'));
        $this->addRule('download_url', $this->_model->_('Invalid URI'), 'uri', null, 'client');
        $this->addElement('text', 'note_url', $this->_model->_('Note url'), array('size' => 80, 'maxlength' => 255));
        $this->addRule('note_url', $this->_model->_('Invalid URI'), 'uri', null, 'client');
        $this->addElement('textarea', 'summary', $this->_model->_('Summary'), array('rows' => 10, 'cols' => 60));
        $this->addElement('altselect', 'allow_reports', $this->_model->_('Allow reports'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('altselect', 'allow_download', $this->_model->_('Allow download'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('selectmodelentity', $this->_model, 'Project', 'Project', $this->_model->_('project'), null, array('size' => 1));
        $this->addElement('text', 'userid', $this->_model->_('User ID'), array('size' => 30, 'maxlength' => 255));
        $this->_onInit($params);
    }

    public function onEntity(Sabai_Model_Entity $entity)
    {
        $defaults = array();
        foreach (array('version', 'stability', 'date', 'download_url', 'note_url', 'summary', 'allow_reports', 'allow_download') as $key) {
            if ($this->elementExists($key) || $this->isInGroup($key)) {
                $defaults[$key] = $entity->getVar($key);
            }
        }
        if ($this->elementExists('Project')) {
            $defaults['Project'] = $entity->getVar('project_id');
        }
        if ($this->elementExists('userid')) {
            $defaults['userid'] = $entity->getVar('userid');
        }
        if (!empty($defaults)) $this->setDefaults($defaults);
        $this->_onEntity($entity);
    }

    public function onFillEntity(Sabai_Model_Entity $entity)
    {
        $vars = array();
        foreach (array('version' => 'version', 'stability' => 'stability', 'date' => 'date', 'download_url' => 'download_url', 'note_url' => 'note_url', 'summary' => 'summary', 'allow_reports' => 'allow_reports', 'allow_download' => 'allow_download', 'project_id' => 'Project', 'userid' => 'userid') as $var_name => $form_name) {
            if ($this->elementExists($form_name) || $this->isInGroup($form_name)) {
                if ($this->getElementType($form_name) == 'static') continue;

                $value = $this->getSubmitValue($form_name);
                $vars[$var_name] = is_array($value) ? array_shift($value) : $value;
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    abstract protected function _onInit(array $params);
    abstract protected function _onEntity(Sabai_Model_Entity $entity);
    abstract protected function _onFillEntity(Sabai_Model_Entity $entity);
}
