<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Xigg_Model_Base_CategoryCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'category_id',
        'created' => 'category_created',
        'updated' => 'category_updated',
        'name' => 'category_name',
        'description' => 'category_description',
        'parent' => 'category_parent',
        'nodeCount' => 'category_node_count',
        'nodeLast' => 'category_node_last',
        'nodeLasttime' => 'category_node_lasttime',
    );
}