<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Xigg/Model/Node2tagHTMLQuickForm.php
*/
abstract class Plugg_Xigg_Model_Base_Node2tagHTMLQuickForm extends Sabai_Model_EntityHTMLQuickForm
{
    public function onInit(array $params)
    {
        $this->addElement('selectmodelentity', $this->_model, 'Node', 'Node', $this->_model->_('node'), null, array('size' => 1));
        $this->addElement('selectmodelentity', $this->_model, 'Tag', 'Tag', $this->_model->_('tag'), null, array('size' => 1));
        $this->_onInit($params);
    }

    public function onEntity(Sabai_Model_Entity $entity)
    {
        $defaults = array();
        if ($this->elementExists('Node')) {
            $defaults['Node'] = $entity->getVar('node_id');
        }
        if ($this->elementExists('Tag')) {
            $defaults['Tag'] = $entity->getVar('tag_id');
        }
        if (!empty($defaults)) $this->setDefaults($defaults);
        $this->_onEntity($entity);
    }

    public function onFillEntity(Sabai_Model_Entity $entity)
    {
        $vars = array();
        foreach (array('node_id' => 'Node', 'tag_id' => 'Tag') as $var_name => $form_name) {
            if ($this->elementExists($form_name) || $this->isInGroup($form_name)) {
                if ($this->getElementType($form_name) == 'static') continue;

                $value = $this->getSubmitValue($form_name);
                $vars[$var_name] = is_array($value) ? array_shift($value) : $value;
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    abstract protected function _onInit(array $params);
    abstract protected function _onEntity(Sabai_Model_Entity $entity);
    abstract protected function _onFillEntity(Sabai_Model_Entity $entity);
}