<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Xigg_Model_Base_NodeCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'node_id',
        'created' => 'node_created',
        'updated' => 'node_updated',
        'title' => 'node_title',
        'source' => 'node_source',
        'sourceTitle' => 'node_source_title',
        'bodyFilterId' => 'node_body_filter_id',
        'body' => 'node_body',
        'bodyHtml' => 'node_body_html',
        'teaserFilterId' => 'node_teaser_filter_id',
        'teaser' => 'node_teaser',
        'teaserHtml' => 'node_teaser_html',
        'published' => 'node_published',
        'allowComments' => 'node_allow_comments',
        'allowTrackbacks' => 'node_allow_trackbacks',
        'allowEdit' => 'node_allow_edit',
        'status' => 'node_status',
        'hidden' => 'node_hidden',
        'priority' => 'node_priority',
        'views' => 'node_views',
        'categoryId' => 'node_category_id',
        'userid' => 'node_userid',
        'commentCount' => 'node_comment_count',
        'commentLast' => 'node_comment_last',
        'commentLasttime' => 'node_comment_lasttime',
        'trackbackCount' => 'node_trackback_count',
        'trackbackLast' => 'node_trackback_last',
        'trackbackLasttime' => 'node_trackback_lasttime',
        'voteCount' => 'node_vote_count',
        'voteLast' => 'node_vote_last',
        'voteLasttime' => 'node_vote_lasttime',
        'viewCount' => 'node_view_count',
        'viewLast' => 'node_view_last',
        'viewLasttime' => 'node_view_lasttime',
    );
}