<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Xigg_Model_Base_Node2tagCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'node2tag_id',
        'created' => 'node2tag_created',
        'updated' => 'node2tag_updated',
        'nodeId' => 'node2tag_node_id',
        'tagId' => 'node2tag_tag_id',
    );
}