<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Xigg_Model_Base_TagCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'tag_id',
        'created' => 'tag_created',
        'updated' => 'tag_updated',
        'name' => 'tag_name',
    );
}