<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Xigg/Model/TagGateway.php
*/
abstract class Plugg_Xigg_Model_Base_TagGateway extends Sabai_Model_Gateway
{
    public function getName()
    {
        return 'tag';
    }

    public function getFields()
    {
        return array('tag_id' => Sabai_Model::KEY_TYPE_INT, 'tag_created' => Sabai_Model::KEY_TYPE_INT, 'tag_updated' => Sabai_Model::KEY_TYPE_INT, 'tag_name' => Sabai_Model::KEY_TYPE_VARCHAR);
    }

    protected function _getSelectByIdQuery($id, array $fields)
    {
        $fields = empty($fields) ? '*' : implode(', ', $fields);
        return sprintf('SELECT %s FROM %stag WHERE tag_id = %d', $fields, $this->_db->getResourcePrefix(), $id);
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, array $fields)
    {
        $fields = empty($fields) ? '*' : implode(', ', $fields);
        return sprintf('SELECT %1$s FROM %2$stag WHERE %3$s', $fields, $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getInsertQuery(array $values)
    {
        $values['tag_created'] = time();
        $values['tag_updated'] = 0;
        return sprintf("INSERT INTO %stag(tag_created, tag_updated, tag_name) VALUES(%d, %d, %s)", $this->_db->getResourcePrefix(), $values['tag_created'], $values['tag_updated'], $this->_db->escapeString($values['tag_name']));
    }

    protected function _getUpdateQuery($id, array $values)
    {
        $last_update = $values['tag_updated'];
        $values['tag_updated'] = time();
        return sprintf("UPDATE %stag SET tag_updated = %d, tag_name = %s WHERE tag_id = %d AND tag_updated = %d", $this->_db->getResourcePrefix(), $values['tag_updated'], $this->_db->escapeString($values['tag_name']), $id, $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$stag WHERE tag_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, array $sets)
    {
        $sets['tag_updated'] = 'tag_updated=' . time();
        return sprintf('UPDATE %stag SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$stag WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$stag WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _beforeDeleteTrigger1($id, array $old)
    {
        return $this->_db->exec(sprintf('DELETE FROM %1$snode2tag WHERE %1$snode2tag.node2tag_tag_id = %2$d', $this->_db->getResourcePrefix(), $id), false);
    }

    protected function _beforeDeleteTrigger($id, array $old)
    {
        if (!$this->_beforeDeleteTrigger1($id, $old)) return false;
        return true;
    }
}