<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/Xigg/Model/Trackback.php
*/
abstract class Plugg_Xigg_Model_Base_Trackback extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Trackback', $model);
        $this->_vars = array('trackback_id' => 0, 'trackback_created' => 0, 'trackback_updated' => 0, 'trackback_title' => null, 'trackback_excerpt' => null, 'trackback_url' => null, 'trackback_blog_name' => null, 'trackback_node_id' => null);
    }

    public function getId()
    {
        return $this->getVar('id');
    }

    public function setId($value)
    {
        $this->setVar('id', $value);
    }

    public function getTimeCreated()
    {
        return $this->getVar('created');
    }

    public function getTimeUpdated()
    {
        return $this->getVar('updated');
    }

    public function getLabel()
    {
        return $this->getVar('title');
    }

    public function assignNode(Sabai_Model_Entity $entity)
    {
        if ($entity->getName() != 'Node') return false;

        return $this->_assignEntity($entity, 'node_id');
    }

    public function unassignNode()
    {
        return $this->_unassignEntity('Node', 'node_id');
    }

    protected function _fetchNode()
    {
        return $this->_fetchEntity('Node', 'node_id');
    }

    protected function _getVar($name)
    {
        return $this->_vars['trackback_' . $name];
    }

    protected function _setVar($name, $value)
    {
        switch ($name) {
        case 'id':
            $this->_vars['trackback_id'] = $value;
            break;
        case 'title':
            $this->_vars['trackback_title'] = trim($value);
            break;
        case 'excerpt':
            $this->_vars['trackback_excerpt'] = trim($value);
            break;
        case 'url':
            $this->_vars['trackback_url'] = trim($value);
            break;
        case 'blog_name':
            $this->_vars['trackback_blog_name'] = trim($value);
            break;
        case 'node_id':
            $this->_vars['trackback_node_id'] = $value;
            break;
        default:
            trigger_error(sprintf('Error trying to set value for variable %s. This variable is either read-only or does not exist for this entity', $name), E_USER_WARNING);
            return false;
        }
        return true;
    }

    protected function _get($name, $sort, $order)
    {
        switch ($name) {
        case 'title':
            return $this->getVar('title');
        case 'excerpt':
            return $this->getVar('excerpt');
        case 'url':
            return $this->getVar('url');
        case 'blog_name':
            return $this->getVar('blog_name');
        case 'Node':
            return $this->_fetchNode();
        }
    }

    public function __set($name, $value)
    {
        switch ($name) {
        case 'title':
            $this->setVar('title', $value);
            break;
        case 'excerpt':
            $this->setVar('excerpt', $value);
            break;
        case 'url':
            $this->setVar('url', $value);
            break;
        case 'blog_name':
            $this->setVar('blog_name', $value);
            break;
        case 'Node':
            $entity = is_array($value) ? $value[0] : $value;
            $this->assignNode($entity);
            break;
        }
    }

    public function initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_Xigg_Model_Base_TrackbackRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Trackback', $model);
    }

    public function fetchByNode($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('trackback_node_id', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByNode($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('Node', $id, $perpage, $sort, $order);
    }

    public function countByNode($id)
    {
        return $this->_countByForeign('trackback_node_id', $id);
    }

    public function fetchByNodeAndCriteria($id, Sabai_Model_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('trackback_node_id', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByNodeAndCriteria($id, Sabai_Model_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('Node', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByNodeAndCriteria($id, Sabai_Model_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('trackback_node_id', $id, $criteria);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_Xigg_Model_Base_TrackbacksByRowset($rs, $this->_model->create('Trackback'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_Xigg_Model_Base_Trackbacks($this->_model, $entities);
    }
}

class Plugg_Xigg_Model_Base_TrackbacksByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Sabai_Model_Entity $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Trackbacks', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_Xigg_Model_Base_Trackbacks extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Trackbacks', $entities);
    }
}