<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Xigg_Model_Base_ViewCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'view_id',
        'created' => 'view_created',
        'updated' => 'view_updated',
        'uid' => 'view_uid',
        'last' => 'view_last',
        'nodeId' => 'view_node_id',
    );
}