<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/OpenID/Model/Assoc.php
*/
abstract class Plugg_OpenID_Model_Base_Assoc extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Assoc', $model);
        $this->_vars = array('assoc_id' => 0, 'assoc_created' => 0, 'assoc_updated' => 0, 'assoc_server_url' => null, 'assoc_handle' => null, 'assoc_secret' => null, 'assoc_issued' => 0, 'assoc_lifetime' => 0, 'assoc_type' => null);
    }

    public function getId()
    {
        return $this->getVar('id');
    }

    public function setId($value)
    {
        $this->setVar('id', $value);
    }

    public function getTimeCreated()
    {
        return $this->getVar('created');
    }

    public function getTimeUpdated()
    {
        return $this->getVar('updated');
    }

    protected function _getVar($name)
    {
        return $this->_vars['assoc_' . $name];
    }

    protected function _setVar($name, $value)
    {
        switch ($name) {
        case 'id':
            $this->_vars['assoc_id'] = $value;
            break;
        case 'server_url':
            $this->_vars['assoc_server_url'] = trim($value);
            break;
        case 'handle':
            $this->_vars['assoc_handle'] = trim($value);
            break;
        case 'secret':
            $this->_vars['assoc_secret'] = $value;
            break;
        case 'issued':
            $this->_vars['assoc_issued'] = $value;
            break;
        case 'lifetime':
            $this->_vars['assoc_lifetime'] = $value;
            break;
        case 'type':
            $this->_vars['assoc_type'] = trim($value);
            break;
        default:
            trigger_error(sprintf('Error trying to set value for variable %s. This variable is either read-only or does not exist for this entity', $name), E_USER_WARNING);
            return false;
        }
        return true;
    }

    protected function _get($name, $sort, $order)
    {
        switch ($name) {
        case 'server_url':
            return $this->getVar('server_url');
        case 'handle':
            return $this->getVar('handle');
        case 'secret':
            return $this->getVar('secret');
        case 'issued':
            return $this->getVar('issued');
        case 'lifetime':
            return $this->getVar('lifetime');
        case 'type':
            return $this->getVar('type');
        }
    }

    public function __set($name, $value)
    {
        switch ($name) {
        case 'server_url':
            $this->setVar('server_url', $value);
            break;
        case 'handle':
            $this->setVar('handle', $value);
            break;
        case 'secret':
            $this->setVar('secret', $value);
            break;
        case 'issued':
            $this->setVar('issued', $value);
            break;
        case 'lifetime':
            $this->setVar('lifetime', $value);
            break;
        case 'type':
            $this->setVar('type', $value);
            break;
        }
    }

    public function initVar($name, $value)
    {
        switch ($name) {
        case 'assoc_secret':
            // use function defined for specific DB. any better way?
            $this->_vars['assoc_secret'] = sabai_db_unescapeBlob($value);
            break;
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_OpenID_Model_Base_AssocRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Assoc', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_OpenID_Model_Base_AssocsByRowset($rs, $this->_model->create('Assoc'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_OpenID_Model_Base_Assocs($this->_model, $entities);
    }
}

class Plugg_OpenID_Model_Base_AssocsByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Sabai_Model_Entity $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Assocs', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_OpenID_Model_Base_Assocs extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Assocs', $entities);
    }
}