<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Birthday_Model_Base_BirthdayCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'birthday_id',
        'created' => 'birthday_created',
        'updated' => 'birthday_updated',
        'year' => 'birthday_year',
        'month' => 'birthday_month',
        'day' => 'birthday_day',
        'userid' => 'birthday_userid',
    );
}