<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Gender_Model_Base_GenderCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'gender_id',
        'created' => 'gender_created',
        'updated' => 'gender_updated',
        'gender' => 'gender_gender',
        'userid' => 'gender_userid',
    );
}