<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Aggregator/Model/ItemHTMLQuickForm.php
*/
abstract class Plugg_Aggregator_Model_Base_ItemHTMLQuickForm extends Sabai_Model_EntityHTMLQuickForm
{
    public function onInit(array $params)
    {
        $this->addElement('text', 'title', $this->_model->_('Title'), array('size' => 80, 'maxlength' => 255));
        $this->addElement('text', 'url', $this->_model->_('Url'), array('size' => 80, 'maxlength' => 255));
        $this->addRule('url', $this->_model->_('Invalid URI'), 'uri', null, 'client');
        $this->addElement('textarea', 'body', $this->_model->_('Body'), array('rows' => 10, 'cols' => 70));
        $this->addElement('text', 'author', $this->_model->_('Author'), array('size' => 80, 'maxlength' => 255));
        $this->addElement('text', 'author_link', $this->_model->_('Author link'), array('size' => 80, 'maxlength' => 255));
        $this->addElement('altselect', 'hidden', $this->_model->_('Hidden'), array(
            1 => $this->_model->_('Yes'),
            0 => $this->_model->_('No'),
        ))->setDelimiter('&nbsp;');
        $this->addElement('selectmodelentity', $this->_model, 'Feed', 'Feed', $this->_model->_('feed'), null, array('size' => 1));
        $this->_onInit($params);
    }

    public function onEntity(Sabai_Model_Entity $entity)
    {
        $defaults = array();
        foreach (array('title', 'url', 'body', 'author', 'author_link', 'hidden') as $key) {
            if ($this->elementExists($key) || $this->isInGroup($key)) {
                $defaults[$key] = $entity->getVar($key);
            }
        }
        if ($this->elementExists('Feed')) {
            $defaults['Feed'] = $entity->getVar('feed_id');
        }
        if (!empty($defaults)) $this->setDefaults($defaults);
        $this->_onEntity($entity);
    }

    public function onFillEntity(Sabai_Model_Entity $entity)
    {
        $vars = array();
        foreach (array('title' => 'title', 'url' => 'url', 'body' => 'body', 'author' => 'author', 'author_link' => 'author_link', 'hidden' => 'hidden', 'feed_id' => 'Feed') as $var_name => $form_name) {
            if ($this->elementExists($form_name) || $this->isInGroup($form_name)) {
                if ($this->getElementType($form_name) == 'static') continue;

                $value = $this->getSubmitValue($form_name);
                $vars[$var_name] = is_array($value) ? array_shift($value) : $value;
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    abstract protected function _onInit(array $params);
    abstract protected function _onEntity(Sabai_Model_Entity $entity);
    abstract protected function _onFillEntity(Sabai_Model_Entity $entity);
}