<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Signature2/library/Signature2/Model/SignatureCriteria.php
*/

class Plugg_Signature2_Model_Base_SignatureCriteria extends Sabai_Model_EntityCriteria
{

    public function idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_id', $value));
    }

    public function idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_id', $value, '>'));
    }

    public function idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_id', $value, '<'));
    }

    public function idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_id', $value, '>='));
    }

    public function idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_id', $value, '<='));
    }

    public function idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('signature_id', $values));
    }

    public function idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('signature_id', $values));
    }

    public function createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_created', $value));
    }

    public function createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_created', $value, '>'));
    }

    public function createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_created', $value, '<'));
    }

    public function createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_created', $value, '>='));
    }

    public function createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_created', $value, '<='));
    }

    public function createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('signature_created', $values));
    }

    public function createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('signature_created', $values));
    }

    public function updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_updated', $value));
    }

    public function updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_updated', $value, '>'));
    }

    public function updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_updated', $value, '<'));
    }

    public function updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_updated', $value, '>='));
    }

    public function updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_updated', $value, '<='));
    }

    public function updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('signature_updated', $values));
    }

    public function updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('signature_updated', $values));
    }

    public function textIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_text', $value));
    }

    public function textStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_text', $str, '^'));
    }

    public function textEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_text', $str, '$'));
    }

    public function textContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_text', $str));
    }

    public function text_filteredIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_text_filtered', $value));
    }

    public function text_filteredStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_text_filtered', $str, '^'));
    }

    public function text_filteredEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_text_filtered', $str, '$'));
    }

    public function text_filteredContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_text_filtered', $str));
    }

    public function text_filter_idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_text_filter_id', $value));
    }

    public function text_filter_idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_text_filter_id', $value, '>'));
    }

    public function text_filter_idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_text_filter_id', $value, '<'));
    }

    public function text_filter_idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_text_filter_id', $value, '>='));
    }

    public function text_filter_idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_text_filter_id', $value, '<='));
    }

    public function text_filter_idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('signature_text_filter_id', $values));
    }

    public function text_filter_idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('signature_text_filter_id', $values));
    }

    public function useridIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('signature_userid', $value));
    }

    public function useridStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_userid', $str, '^'));
    }

    public function useridEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_userid', $str, '$'));
    }

    public function useridContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('signature_userid', $str));
    }

    public function useridIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('signature_userid', $values));
    }

    public function useridNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('signature_userid', $values));
    }
}