<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/Page/Model/Page.php
*/
require_once 'Sabai/Model/TreeEntity.php';

abstract class Plugg_Page_Model_Base_Page extends Sabai_Model_TreeEntity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Page', $model);
        $this->_vars = array('page_id' => 0, 'page_created' => 0, 'page_updated' => 0, 'page_title' => null, 'page_slug' => null, 'page_htmlhead' => null, 'page_content' => null, 'page_content_html' => null, 'page_content_filter_id' => 0, 'page_allow_edit' => 1, 'page_allow_comment' => 1, 'page_lock' => 0, 'page_nav' => 0, 'page_views' => 0, 'page_hidden' => 0, 'page_parent' => null, 'page_userid' => null);
    }

    public function getUserId()
    {
        return $this->getVar('userid');
    }

    public function assignUser($user)
    {
        $this->_setVar('userid', $user->getId());
    }

    protected function _fetchUser($withData = false)
    {
        if (!isset($this->_objects['User'])) {
            $user_id = $this->getUserId();
            $identities = $this->_model->fetchUserIdentities(array($user_id), $withData);
            $this->_objects['User'] = $identities[$user_id];
        }
        return $this->_objects['User'];
    }

    public function isOwnedBy($user)
    {
        return $this->getUserId() == $user->getId();
    }

    public function getId()
    {
        return $this->getVar('id');
    }

    public function setId($value)
    {
        $this->setVar('id', $value);
    }

    public function getTimeCreated()
    {
        return $this->getVar('created');
    }

    public function getTimeUpdated()
    {
        return $this->getVar('updated');
    }

    public function getLabel()
    {
        return $this->getVar('title');
    }

    public function getParentId()
    {
        return intval($this->getVar('parent'));
    }

    public function assignParent(Sabai_Model_Entity $entity)
    {
        if ($entity->getName() != 'Page') return false;

        return $this->_assignEntity($entity, 'parent');
    }

    public function unassignParent()
    {
        return $this->_unassignEntity('Parent', 'parent');
    }

    protected function _fetchParent()
    {
        return $this->_fetchEntity('Page', 'parent');
    }

    protected function _getVar($name)
    {
        return $this->_vars['page_' . $name];
    }

    protected function _setVar($name, $value)
    {
        switch ($name) {
        case 'id':
            $this->_vars['page_id'] = $value;
            break;
        case 'title':
            $this->_vars['page_title'] = trim($value);
            break;
        case 'slug':
            $this->_vars['page_slug'] = trim($value);
            break;
        case 'htmlhead':
            $this->_vars['page_htmlhead'] = trim($value);
            break;
        case 'content':
            $this->_vars['page_content'] = trim($value);
            break;
        case 'content_html':
            $this->_vars['page_content_html'] = trim($value);
            break;
        case 'content_filter_id':
            $this->_vars['page_content_filter_id'] = $value;
            break;
        case 'allow_edit':
            $this->_vars['page_allow_edit'] = $value;
            break;
        case 'allow_comment':
            $this->_vars['page_allow_comment'] = $value;
            break;
        case 'lock':
            $this->_vars['page_lock'] = $value;
            break;
        case 'nav':
            $this->_vars['page_nav'] = $value;
            break;
        case 'views':
            $this->_vars['page_views'] = $value;
            break;
        case 'hidden':
            $this->_vars['page_hidden'] = $value;
            break;
        case 'parent':
            $this->_vars['page_parent'] = $value;
            break;
        case 'userid':
            $this->_vars['page_userid'] = trim($value);
            break;
        default:
            trigger_error(sprintf('Error trying to set value for variable %s. This variable is either read-only or does not exist for this entity', $name), E_USER_WARNING);
            return false;
        }
        return true;
    }

    protected function _get($name, $sort, $order)
    {
        switch ($name) {
        case 'title':
            return $this->getVar('title');
        case 'slug':
            return $this->getVar('slug');
        case 'htmlhead':
            return $this->getVar('htmlhead');
        case 'content':
            return $this->getVar('content');
        case 'content_html':
            return $this->getVar('content_html');
        case 'content_filter_id':
            return $this->getVar('content_filter_id');
        case 'allow_edit':
            return $this->getVar('allow_edit');
        case 'allow_comment':
            return $this->getVar('allow_comment');
        case 'lock':
            return $this->getVar('lock');
        case 'nav':
            return $this->getVar('nav');
        case 'views':
            return $this->getVar('views');
        case 'hidden':
            return $this->getVar('hidden');
        case 'Parent':
            return $this->_fetchParent();
        case 'User':
            return $this->_fetchUser();
        case 'UserWithData':
            return $this->_fetchUser(true);
        case 'Children':
            return $this->_fetchChildren();
        }
    }

    public function __set($name, $value)
    {
        switch ($name) {
        case 'title':
            $this->setVar('title', $value);
            break;
        case 'slug':
            $this->setVar('slug', $value);
            break;
        case 'htmlhead':
            $this->setVar('htmlhead', $value);
            break;
        case 'content':
            $this->setVar('content', $value);
            break;
        case 'content_html':
            $this->setVar('content_html', $value);
            break;
        case 'content_filter_id':
            $this->setVar('content_filter_id', $value);
            break;
        case 'allow_edit':
            $this->setVar('allow_edit', $value);
            break;
        case 'allow_comment':
            $this->setVar('allow_comment', $value);
            break;
        case 'lock':
            $this->setVar('lock', $value);
            break;
        case 'nav':
            $this->setVar('nav', $value);
            break;
        case 'views':
            $this->setVar('views', $value);
            break;
        case 'hidden':
            $this->setVar('hidden', $value);
            break;
        case 'Parent':
            $entity = is_array($value) ? $value[0] : $value;
            $this->assignParent($entity);
            break;
        }
    }

    public function initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

require_once 'Sabai/Model/TreeEntityRepository.php';

abstract class Plugg_Page_Model_Base_PageRepository extends Sabai_Model_TreeEntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Page', $model);
    }
    public function fetchByUser($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('page_userid', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByUser($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('User', $id, $perpage, $sort, $order);
    }

    public function countByUser($id)
    {
        return $this->_countByForeign('page_userid', $id);
    }

    public function fetchByUserAndCriteria($id, Sabai_Model_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('page_userid', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByUserAndCriteria($id, Sabai_Model_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('User', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByUserAndCriteria($id, Sabai_Model_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('page_userid', $id, $criteria);
    }

    public function fetchByParent($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('page_parent', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByParent($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('Parent', $id, $perpage, $sort, $order);
    }

    public function countByParent($id)
    {
        return $this->_countByForeign('page_parent', $id);
    }

    public function fetchByParentAndCriteria($id, Sabai_Model_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('page_parent', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByParentAndCriteria($id, Sabai_Model_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('Parent', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByParentAndCriteria($id, Sabai_Model_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('page_parent', $id, $criteria);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_Page_Model_Base_PagesByRowset($rs, $this->_model->create('Page'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_Page_Model_Base_Pages($this->_model, $entities);
    }
}

class Plugg_Page_Model_Base_PagesByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Sabai_Model_Entity $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Pages', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
        if (isset($row['level'])) {
            $entity->setParentsCount($row['level']);
        }
        $entity->left = $row['tree_left'];
        $entity->right = $row['tree_right'];
    }
}

class Plugg_Page_Model_Base_Pages extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Pages', $entities);
    }
}