<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/Locale/Model/Message.php
*/
abstract class Plugg_Locale_Model_Base_Message extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Message', $model);
        $this->_vars = array('message_id' => 0, 'message_created' => 0, 'message_updated' => 0, 'message_key' => null, 'message_lang' => null, 'message_localized' => null, 'message_plugin' => null);
    }

    public function getId()
    {
        return $this->getVar('id');
    }

    public function setId($value)
    {
        $this->setVar('id', $value);
    }

    public function getTimeCreated()
    {
        return $this->getVar('created');
    }

    public function getTimeUpdated()
    {
        return $this->getVar('updated');
    }

    public function getLabel()
    {
        return $this->getVar('key');
    }

    protected function _getVar($name)
    {
        return $this->_vars['message_' . $name];
    }

    protected function _setVar($name, $value)
    {
        switch ($name) {
        case 'id':
            $this->_vars['message_id'] = $value;
            break;
        case 'key':
            $this->_vars['message_key'] = trim($value);
            break;
        case 'lang':
            $this->_vars['message_lang'] = trim($value);
            break;
        case 'localized':
            $this->_vars['message_localized'] = trim($value);
            break;
        case 'plugin':
            $this->_vars['message_plugin'] = trim($value);
            break;
        default:
            trigger_error(sprintf('Error trying to set value for variable %s. This variable is either read-only or does not exist for this entity', $name), E_USER_WARNING);
            return false;
        }
        return true;
    }

    protected function _get($name, $sort, $order)
    {
        switch ($name) {
        case 'key':
            return $this->getVar('key');
        case 'lang':
            return $this->getVar('lang');
        case 'localized':
            return $this->getVar('localized');
        case 'plugin':
            return $this->getVar('plugin');
        }
    }

    public function __set($name, $value)
    {
        switch ($name) {
        case 'key':
            $this->setVar('key', $value);
            break;
        case 'lang':
            $this->setVar('lang', $value);
            break;
        case 'localized':
            $this->setVar('localized', $value);
            break;
        case 'plugin':
            $this->setVar('plugin', $value);
            break;
        }
    }

    public function initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_Locale_Model_Base_MessageRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Message', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_Locale_Model_Base_MessagesByRowset($rs, $this->_model->create('Message'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_Locale_Model_Base_Messages($this->_model, $entities);
    }
}

class Plugg_Locale_Model_Base_MessagesByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Sabai_Model_Entity $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Messages', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_Locale_Model_Base_Messages extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Messages', $entities);
    }
}