<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/User/Model/Activewidget.php
*/
abstract class Plugg_User_Model_Base_Activewidget extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Activewidget', $model);
        $this->_vars = array('activewidget_id' => 0, 'activewidget_created' => 0, 'activewidget_updated' => 0, 'activewidget_title' => null, 'activewidget_order' => 0, 'activewidget_private' => 0, 'activewidget_position' => 0, 'activewidget_settings' => null, 'activewidget_widget_id' => null);
    }

    public function getId()
    {
        return $this->getVar('id');
    }

    public function setId($value)
    {
        $this->setVar('id', $value);
    }

    public function getTimeCreated()
    {
        return $this->getVar('created');
    }

    public function getTimeUpdated()
    {
        return $this->getVar('updated');
    }

    public function assignWidget(Sabai_Model_Entity $entity)
    {
        if ($entity->getName() != 'Widget') return false;

        return $this->_assignEntity($entity, 'widget_id');
    }

    public function unassignWidget()
    {
        return $this->_unassignEntity('Widget', 'widget_id');
    }

    protected function _fetchWidget()
    {
        return $this->_fetchEntity('Widget', 'widget_id');
    }

    protected function _getVar($name)
    {
        return $this->_vars['activewidget_' . $name];
    }

    protected function _setVar($name, $value)
    {
        switch ($name) {
        case 'id':
            $this->_vars['activewidget_id'] = $value;
            break;
        case 'title':
            $this->_vars['activewidget_title'] = trim($value);
            break;
        case 'order':
            $this->_vars['activewidget_order'] = $value;
            break;
        case 'private':
            $this->_vars['activewidget_private'] = $value;
            break;
        case 'position':
            $this->_vars['activewidget_position'] = $value;
            break;
        case 'settings':
            $this->_vars['activewidget_settings'] = trim($value);
            break;
        case 'widget_id':
            $this->_vars['activewidget_widget_id'] = $value;
            break;
        default:
            trigger_error(sprintf('Error trying to set value for variable %s. This variable is either read-only or does not exist for this entity', $name), E_USER_WARNING);
            return false;
        }
        return true;
    }

    protected function _get($name, $sort, $order)
    {
        switch ($name) {
        case 'title':
            return $this->getVar('title');
        case 'order':
            return $this->getVar('order');
        case 'private':
            return $this->getVar('private');
        case 'position':
            return $this->getVar('position');
        case 'settings':
            return $this->getVar('settings');
        case 'Widget':
            return $this->_fetchWidget();
        }
    }

    public function __set($name, $value)
    {
        switch ($name) {
        case 'title':
            $this->setVar('title', $value);
            break;
        case 'order':
            $this->setVar('order', $value);
            break;
        case 'private':
            $this->setVar('private', $value);
            break;
        case 'position':
            $this->setVar('position', $value);
            break;
        case 'settings':
            $this->setVar('settings', $value);
            break;
        case 'Widget':
            $entity = is_array($value) ? $value[0] : $value;
            $this->assignWidget($entity);
            break;
        }
    }

    public function initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_User_Model_Base_ActivewidgetRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Activewidget', $model);
    }

    public function fetchByWidget($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('activewidget_widget_id', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByWidget($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('Widget', $id, $perpage, $sort, $order);
    }

    public function countByWidget($id)
    {
        return $this->_countByForeign('activewidget_widget_id', $id);
    }

    public function fetchByWidgetAndCriteria($id, Sabai_Model_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('activewidget_widget_id', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByWidgetAndCriteria($id, Sabai_Model_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('Widget', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByWidgetAndCriteria($id, Sabai_Model_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('activewidget_widget_id', $id, $criteria);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_User_Model_Base_ActivewidgetsByRowset($rs, $this->_model->create('Activewidget'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_User_Model_Base_Activewidgets($this->_model, $entities);
    }
}

class Plugg_User_Model_Base_ActivewidgetsByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Sabai_Model_Entity $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Activewidgets', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_User_Model_Base_Activewidgets extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Activewidgets', $entities);
    }
}