<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_FieldCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'field_id',
        'created' => 'field_created',
        'updated' => 'field_updated',
        'name' => 'field_name',
        'title' => 'field_title',
        'plugin' => 'field_plugin',
        'order' => 'field_order',
        'active' => 'field_active',
        'type' => 'field_type',
        'registerable' => 'field_registerable',
        'editable' => 'field_editable',
        'viewable' => 'field_viewable',
        'configurable' => 'field_configurable',
    );
}