<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_MenuCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'menu_id',
        'created' => 'menu_created',
        'updated' => 'menu_updated',
        'name' => 'menu_name',
        'plugin' => 'menu_plugin',
        'title' => 'menu_title',
        'type' => 'menu_type',
        'order' => 'menu_order',
        'active' => 'menu_active',
    );
}