<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_PanelwidgetCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'panelwidget_id',
        'created' => 'panelwidget_created',
        'updated' => 'panelwidget_updated',
        'title' => 'panelwidget_title',
        'order' => 'panelwidget_order',
        'private' => 'panelwidget_private',
        'position' => 'panelwidget_position',
        'settings' => 'panelwidget_settings',
        'panelId' => 'panelwidget_panel_id',
        'widgetId' => 'panelwidget_widget_id',
    );
}