<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_TabCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'tab_id',
        'created' => 'tab_created',
        'updated' => 'tab_updated',
        'name' => 'tab_name',
        'title' => 'tab_title',
        'plugin' => 'tab_plugin',
        'order' => 'tab_order',
        'active' => 'tab_active',
        'type' => 'tab_type',
        'private' => 'tab_private',
    );
}