<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Search_Model_Base_SearchableCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'searchable_id',
        'created' => 'searchable_created',
        'updated' => 'searchable_updated',
        'name' => 'searchable_name',
        'title' => 'searchable_title',
        'plugin' => 'searchable_plugin',
        'order' => 'searchable_order',
        'default' => 'searchable_default',
    );
}